"""Add PipelineRun model

Revision ID: 0f99f72339c5
Revises: eb9fab28640a
Create Date: 2026-05-17 18:24:07.874427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f99f72339c5'
down_revision: Union[str, None] = 'eb9fab28640a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pipelines_selected', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_company_name'), 'pipeline_runs', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_company_name'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
