"""add_opportunity_category_to_signals

Revision ID: bdfbdd61de53
Revises: 0f99f72339c5
Create Date: 2026-05-17 19:56:45.175019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bdfbdd61de53'
down_revision: Union[str, None] = '0f99f72339c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_pain_signals', sa.Column('opportunity_category', sa.String(length=100), nullable=True))
    op.add_column('signals', sa.Column('opportunity_category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'opportunity_category')
    op.drop_column('market_pain_signals', 'opportunity_category')
    # ### end Alembic commands ###
