"""add unique constraint

Revision ID: eb72991dff4b
Revises: f6da00a35400
Create Date: 2026-05-16 20:46:19.012798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb72991dff4b'
down_revision: Union[str, Sequence[str], None] = 'f6da00a35400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('normalized_signals', 'github_signal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('normalized_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('normalized_signals_raw_signal_id_fkey'), 'normalized_signals', type_='foreignkey')
    op.drop_column('normalized_signals', 'raw_signal_id')
    op.drop_constraint(op.f('unique_external_id'), 'raw_signals', type_='unique')
    op.create_unique_constraint('uq_source_external_id', 'raw_signals', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_external_id', 'raw_signals', type_='unique')
    op.create_unique_constraint(op.f('unique_external_id'), 'raw_signals', ['external_id'], postgresql_nulls_not_distinct=False)
    op.add_column('normalized_signals', sa.Column('raw_signal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('normalized_signals_raw_signal_id_fkey'), 'normalized_signals', 'raw_signals', ['raw_signal_id'], ['id'])
    op.alter_column('normalized_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('normalized_signals', 'github_signal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
