"""Add job specific fields to signals

Revision ID: eb9fab28640a
Revises: 0001_initial
Create Date: 2026-05-17 18:03:21.793204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb9fab28640a'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('huggingface_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_table('raw_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    op.create_table('tracked_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiring_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('posted_date', sa.String(length=100), nullable=True),
    sa.Column('sanitized_description', sa.Text(), nullable=True),
    sa.Column('detected_tech_stack', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_pain_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('company_name_detected', sa.String(length=255), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('workflows', sa.JSON(), nullable=True),
    sa.Column('pain_category', sa.String(length=100), nullable=True),
    sa.Column('pain_subcategories', sa.JSON(), nullable=True),
    sa.Column('workflow_pains', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('tech_confidence', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('business_relevance', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('strategic_fit_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('capability_matches', sa.JSON(), nullable=True),
    sa.Column('matched_practices', sa.JSON(), nullable=True),
    sa.Column('matched_accelerators', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_pain_signals_company_id'), 'market_pain_signals', ['company_id'], unique=False)
    op.create_table('normalized_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_signal_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['github_signal_id'], ['github_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('companies_name_key'), 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.add_column('signals', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('signals', sa.Column('urgency', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('signals_company_id_fkey'), 'signals', type_='foreignkey')
    op.create_foreign_key(None, 'signals', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.create_foreign_key(op.f('signals_company_id_fkey'), 'signals', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('signals', 'urgency')
    op.drop_column('signals', 'location')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_unique_constraint(op.f('companies_name_key'), 'companies', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_table('normalized_signals')
    op.drop_index(op.f('ix_market_pain_signals_company_id'), table_name='market_pain_signals')
    op.drop_table('market_pain_signals')
    op.drop_table('hiring_signals')
    op.drop_table('funding_events')
    op.drop_table('tracked_queries')
    op.drop_table('raw_signals')
    op.drop_table('huggingface_signals')
    op.drop_table('github_signals')
    # ### end Alembic commands ###
